### ISSUE TITLE
Excel tables references

### ISSUE THREAD

**Issue by millergarym** [PerfectXL/XLParser#16]
Table references aren't implemented.
eg [@Column1] Table1[@Column1] =Table1[[#Headers],[Column1]]

**Comment by dhoepelman** [comment]
[Microsoft support page](https://support.office.com/en-us/article/Using-structured-references-with-Excel-tables-f5ed2452-2337-4f71-bed3-c8ae6d2b276e) on the subject.
New feature in Excel 2007, which explains why it isn't encountered in the EUSES and Enron data sets.

It should be part of reference expression, and is essentially another way to reference a range.

In the official grammar, its description starts at `structure-reference`

**Comment by dhoepelman** [comment]
It's a bit complicated to support, as what Excel stores is not always the same as what the user sees/enters.
This seems most prominent with the "@" operator. `=Table[@Column]` is internally stored as `=Table[[#This Row],[Sales]]`.

As XLParser is primarily intended to parse existing excel files, it is probably best to only parse what Excel actually stores.

**Comment by dhoepelman** [comment]
Added in #20, will be in 1.2

**Comment by dhoepelman** [comment]
Note that the "@" operator doesn't get special consideration, it is parsed as if it was just a column name.
